<Project>
  <!-- Disable all code analysis for Docker builds -->
  <PropertyGroup>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors></WarningsAsErrors>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <CodeAnalysisRuleSet></CodeAnalysisRuleSet>
  </PropertyGroup>
</Project>
