<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <!-- Disable code analysis warnings that are not appropriate for test projects -->
    <!-- CA1515: Test classes must be public for xUnit, conflicts with this rule -->
    <NoWarn>CA1707;CA1307;CA1849;CA2007;MA0074;CS1591;AsyncFixer02;VSTHRD103;CA1515;IDISP003;IDISP005;IDISP016;IDISP017;CA1802;CA1835</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="NetArchTest.Rules" Version="1.3.2" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="Xunit.SkippableFact" Version="1.4.13" />
    <PackageReference Include="Jellyfin.Controller" Version="10.10.7" />
    <PackageReference Include="Jellyfin.Model" Version="10.10.7" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jellyfin.Xtream\Jellyfin.Xtream.csproj" />
  </ItemGroup>
</Project>
